### ISSUE TITLE
Issue description's text color in active projects page

### ISSUE THREAD

**Issue by kasper42721** [NSP-Community/NSP#121]
![screenshot 1](https://user-images.githubusercontent.com/42063801/43642263-85a1b7d8-9744-11e8-8733-7747fb8ab9ac.png)
The issue description's color makes it so that it is not visible

**Comment by rshrc** [comment]
Yeah this bug is caused to improper configuration of the css files, inside or outside the html templates. It is a minor bug but pretty hard to track down.

**Comment by rshrc** [comment]
The code will be updated in the serer soon. Cheers
